---
- name: Push variables file
  template:
    src: vars.sh.j2
    dest: {{ standalone_home_dir}}/vars.sh
    owner: {{ standalone_user }}
    group: {{ standalone_user }}
    mode: 0755

- name: Push standalone parameters file
  template:
    src: standalone_parameters.yaml.j2
    dest: {{ standalone_home_dir}}/standalone_parameters.yaml
    owner: {{ standalone_user }}
    group: {{ standalone_user }}
    mode: 0755

- name: Run container image prepare
  shell: |
    openstack tripleo container image prepare default --local-push-destination \
    --output-env-file containers-prepare-parameters.yaml

- name: Deploy Standalone
  shell: |
    source vars.sh
    sudo openstack tripleo deploy \
      --templates \
      --local-ip={{ standalone_ip }}/{{ standalone_netmask }} \
      --control-virtual-ip {{ standalone_vip }} \
      -e /usr/share/openstack-tripleo-heat-templates/environments/standalone/standalone-tripleo.yaml \
      -r /usr/share/openstack-tripleo-heat-templates/roles/Standalone.yaml \
      -e $HOME/containers-prepare-parameters.yaml \
      -e $HOME/standalone_parameters.yaml \
      --output-dir {{ standalone_home_dir }} \
      --standalone-role Standalone
