---
- name: Configure hostname
  become: true
  shell: |
    hostnamectl set-hostname standalone.example.com
    hostnamectl set-hostname standalone.example.com --transient

- name: Set delorean repositories
  become: true
  shell: |
    curl https://trunk.rdoproject.org/centos9-zed/current/delorean.repo --output /etc/yum.repos.d/delorean.repo
    curl https://trunk.rdoproject.org/centos9-zed/delorean-deps.repo --output /etc/yum.repos.d/delorean-deps.repo

- name: Enable crb if needed
  ignore_errors: true
  become: true
  shell: |
    yum-config-manager --enable  crb

- name: Disable ssl verify is needed
  become: true
  shell: |
    sed -i '$a\sslverify\=false' /etc/yum.conf

- name: Install tripleoclient
  become: true
  shell: |
    dnf install python3-tripleoclient -y

- name: Create Stack user
  become: true
  shell: |
    adduser stack
    echo "stack ALL=(root) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/stack
    chmod 0440 /etc/sudoers.d/stack
    cp -R /root/.ssh /home/stack/
    chown -R stack:stack /home/stack/.ssh
