---
# service name and file location
services:
  # Service name
  keystone:
    # Bool to enable/disable a service (not implemented yet)
    enable: true
    # Pod name, in both OCP and podman context.
    # It could be strict match or will only just grep the podman_name
    # and work with all the pods which matched with pod_name.
    # To enable/disable use strict_pod_name_match: true/false
    podman_name: keystone
    pod_name: keystone
    # pod options
    # strict match for getting pod id in TripleO and podman context
    strict_pod_name_match: true
    # Path of the config files you want to analyze.
    # It could be whatever path you want:
    # /etc/<service_name> or /etc or /usr/share/<something> or even /
    # @TODO: need to implement loop over path to support multiple paths such as:
    # - /etc
    # - /usr/share
    path:
      - /etc/keystone
    # In podman context, when you want to pull specific files:
    # You need to set pull_items to true
    # This is not working with the `path` list, the path needs to be a full path
    # and the `path`key:value will be ignored.
    file_name:
      - /etc/keystone/keystone.conf
      - /etc/keystone/logging.conf
  glance:
    enable: true
    podman_name: glance
    pod_name: glance
    strict_pod_name_match: false
    path:
      - /etc/glance
    file_name:
      - /etc/glance/glance-api.conf
  nova:
    enable: true
    pod_name: nova
    strict_pod_name_match: false
    path:
      - /etc/nova
  neutron:
    enable: true
    podman_name: neutron
    pod_name: neutron
    strict_pod_name_match: false
    path:
      - /etc/neutron
  neutron-openvswitch:
    enable: true
    podman_name: neutron-openvswitch
    pod_name: neutron-openvswitch
    strict_pod_name_match: false
    path: 
      - /etc/neutron
  neutron-l3:
    enable: true
    podman_name: neutron-l3
    pod_name: neutron-l3
    strict_pod_name_match: false
    path: 
      - /etc/neutron
  mariadb:
    enable: true
    podman_name: mariadb
    pod_name: mariadb-openstack
    strict_pod_name_match: true
    path:
      - /etc
  rabbitmq:
    enable: true
    podman_name: rabbitmq
    pod_name: rabbitmq
    strict_pod_name_match: false
    path: 
      - /etc/rabbitmq