---
# Path where the config files should be pulled
tripleo_collect_dir: /tmp/collect_tripleo_configs
crc_collect_dir: /tmp/collect_crc_configs
working_dir: /tmp
local_working_dir: /tmp

collect_podman: false
collect_ocp: false

# OCP auth config
oc_host: https://api.crc.testing:6443
oc_login: kubeadmin
oc_passwd: 12345678

pull_items: false
