---
- block:
  - name: Get oc binary path
    register: oc_result
    shell: |
      which oc

  - name: Set fact for oc binary
    set_fact:
      oc_bin: "{{ oc_result.stdout }}"

  - name: Login to OC
    shell: |
      {{ oc_bin }} login -u {{ oc_login }} -p {{ oc_passwd }} {{ oc_host }}

  - name: Test login
    shell: |
      {{ oc_bin }} whoami

  - name: Get pods id
    register: results
    shell: |
      {{ oc_bin }} get pods --field-selector status.phase=Running | awk '/{{ service.value.pod_name }}-[a-f0-9-]/ {print $1}'

  - name: Set fact for pod id
    set_fact:
      pod_id: "{{ results.stdout }}"

  - name: Set fact for {{ service.key }} path
    set_fact:
      config_path: "{{ service.value.path }}"

  - name: Create {{ service.key }} directory
    become: true
    file:
      path: "{{ working_dir }}/ocp/{{ config_path }}"
      state: directory
      mode: "0755"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      recurse: true

  - name: Pull configuration files from {{ service }} pod
    register: config_results
    shell: |
      {{ oc_bin }} cp {{ pod_id }}:{{ config_path }}/ {{ working_dir }}/ocp/{{ config_path }}/
