---
- block:
  - name: Get oc binary path
    register: crc_result
    shell: |
      eval $(crc oc-env)
      which oc
    when: crc

  - name: Set fact for oc binary
    set_fact:
      oc_bin: "{{ crc_result.stdout }}"
    when: crc

  - name: Get oc binary path
    register: oc_result
    shell: |
      which oc
    when: not crc

  - name: Set fact for oc binary
    set_fact:
      oc_bin: "{{ oc_result.stdout }}"
    when: not crc

  - name: Login to OC
    shell: |
      {{ oc_bin }} login -u {{ oc_login }} -p {{ oc_passwd }} {{ oc_host }}

  - name: Test login
    shell: |
      {{ oc_bin }} whoami